#!/usr/bin/env python3
"""
living-memory index generator.

Scans doc/_*.md (permanents) and doc/log/*.md (logs),
parses L1 metadata blocks, and generates doc/_INDEX.md.

Usage:
    python generate-index.py              # from project root
    python generate-index.py /path/to/doc # custom doc directory

Idempotent: running twice produces the same output.
Zero dependencies: Python 3.8+ standard library only.
"""

import os
import re
import sys
from datetime import datetime
from pathlib import Path


def find_doc_dir():
    """Find the doc/ directory."""
    if len(sys.argv) > 1:
        doc_dir = Path(sys.argv[1])
    else:
        doc_dir = Path("doc")

    if not doc_dir.is_dir():
        print(f"No '{doc_dir}' directory found. Nothing to index.")
        sys.exit(0)

    return doc_dir


def parse_l1(filepath):
    """Extract L1 metadata from a file."""
    try:
        content = filepath.read_text(encoding="utf-8")
    except (OSError, UnicodeDecodeError):
        return None

    match = re.search(
        r"<!--\s*L1_START\s*-->(.+?)<!--\s*L1_END\s*-->",
        content,
        re.DOTALL,
    )
    if not match:
        return None

    block = match.group(1)
    meta = {}
    for line in block.splitlines():
        line = line.strip()
        if line.startswith("#") or not line:
            continue
        if ":" in line:
            key, _, value = line.partition(":")
            meta[key.strip().lower()] = value.strip()

    return meta


def collect_docs(doc_dir):
    """Collect permanents and logs with their L1 metadata."""
    permanents = []
    logs = []

    # Permanent docs: doc/_*.md
    for f in sorted(doc_dir.glob("_*.md")):
        if f.name == "_INDEX.md":
            continue
        meta = parse_l1(f)
        if meta:
            permanents.append((f, meta))

    # Log docs: doc/log/*.md
    log_dir = doc_dir / "log"
    if log_dir.is_dir():
        for f in sorted(log_dir.glob("*.md"), reverse=True):
            meta = parse_l1(f)
            if meta:
                logs.append((f, meta))

    return permanents, logs


def generate_index(doc_dir, permanents, logs):
    """Generate _INDEX.md content."""
    now = datetime.now().strftime("%Y-%m-%d %H:%M")
    lines = [
        f"# Project Knowledge Index",
        f"",
        f"> Auto-generated by [living-memory](https://github.com/ralpha/living-memory) on {now}.",
        f"> Do not edit manually — rebuilt from L1 metadata on every commit.",
        f"",
    ]

    # Permanents section
    lines.append("## Permanent docs")
    lines.append("")
    if permanents:
        lines.append("| Document | Subject | Status | Category |")
        lines.append("|----------|---------|--------|----------|")
        for f, meta in permanents:
            name = f.name
            subject = meta.get("subject", "—")
            status = meta.get("status", "—")
            category = meta.get("category", "—")
            rel_path = f.relative_to(doc_dir.parent)
            lines.append(f"| [{name}]({rel_path}) | {subject} | {status} | {category} |")
    else:
        lines.append("_No permanent docs yet. Create one with `templates/permanent.md`._")
    lines.append("")

    # Logs section (last 20)
    lines.append("## Recent logs")
    lines.append("")
    display_logs = logs[:20]
    if display_logs:
        lines.append("| Date | Subject | Status | Category |")
        lines.append("|------|---------|--------|----------|")
        for f, meta in display_logs:
            date = meta.get("date", f.stem[:10])
            subject = meta.get("subject", "—")
            status = meta.get("status", "—")
            category = meta.get("category", "—")
            rel_path = f.relative_to(doc_dir.parent)
            lines.append(f"| {date} | [{subject}]({rel_path}) | {status} | {category} |")
        if len(logs) > 20:
            lines.append(f"")
            lines.append(f"_{len(logs) - 20} older logs not shown._")
    else:
        lines.append("_No logs yet. Create one with `templates/log.md`._")
    lines.append("")

    # Stats
    lines.append("---")
    lines.append(f"**{len(permanents)}** permanent docs, **{len(logs)}** logs.")
    lines.append("")

    return "\n".join(lines)


def main():
    doc_dir = find_doc_dir()
    permanents, logs = collect_docs(doc_dir)
    index_content = generate_index(doc_dir, permanents, logs)

    index_path = doc_dir / "_INDEX.md"
    index_path.write_text(index_content, encoding="utf-8")
    print(f"Generated {index_path} ({len(permanents)} permanents, {len(logs)} logs)")


if __name__ == "__main__":
    main()
